
#pragma once

#include "Components/Button.h"

#include "StarfireButton.generated.h"

UCLASS( HideCategories="Event" )
class STARFIREUI_API UStarfireButton : public UButton
{
	GENERATED_BODY( )
public:
	// Constructor
	UStarfireButton( );

	// Various delegates for the events that can be generated by a button
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam( FOnSFButtonClickedEvent, UStarfireButton*, Button );
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam( FOnSFButtonPressedEvent, UStarfireButton*, Button );
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam( FOnSFButtonReleasedEvent, UStarfireButton*, Button );
	DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam( FOnSFButtonHoverEvent, UStarfireButton*, Button );
	
	// Called when the button is clicked
	UPROPERTY(BlueprintAssignable, Category="StarfireButton|SFEvent")
	FOnSFButtonClickedEvent OnClickedSF;

	// Called when the button is pressed
	UPROPERTY(BlueprintAssignable, Category="StarfireButton|sFEvent")
	FOnSFButtonPressedEvent OnPressedSF;

	// Called when the button is released
	UPROPERTY(BlueprintAssignable, Category="StarfireButton|SFEvent")
	FOnSFButtonReleasedEvent OnReleasedSF;

	// Called when the mouse cursor starts to overlap
	UPROPERTY( BlueprintAssignable, Category = "StarfireButton|SFEvent" )
	FOnSFButtonHoverEvent OnHoveredSF;

	// Called when the mouse cursor end its overlap
	UPROPERTY( BlueprintAssignable, Category = "StarfireButton|SFEvent" )
	FOnSFButtonHoverEvent OnUnhoveredSF;

	// Update all button states with a single common texture
	UFUNCTION( BlueprintCallable, Category = "StarfireButton" )
	void UpdateImage( UTexture2D *NewImage );

	// Update all button states with a common color (and a .5 alpha for the disabled state)
	UFUNCTION( BlueprintCallable, Category = "StarfireButton" )
	void UpdateTint( FLinearColor NewColor );

protected:
#if WITH_EDITOR
	// Widget API
	const FText GetPaletteCategory( ) override;
#endif

private:
	// Delegate handler for the base type click event to trigger OnCoreClicked
	UFUNCTION( )
	void ButtonClicked( );
	
	// Delegate handler for the base type pressed event to trigger OnCorePressed
	UFUNCTION( )
	void ButtonPressed( );

	// Delegate handler for the base type released event to trigger OnCoreReleased
	UFUNCTION( )
	void ButtonReleased( );
	
	// Delegate handler for the base type hover event to trigger OnCoreHovered
	UFUNCTION( )
	void ButtonHover( );
	
	// Delegate handler for the base type unhover event to trigger OnCoreUnhovered
	UFUNCTION( )
	void ButtonUnhover( );
};